### ISSUE TITLE
ValueError: Invalid value of type 'builtins.str' received for the 'textposition' property of scatter - Received value: 'centre'

### ISSUE THREAD

**Issue by evolving6000** [mukund109/word-mesh#3]
Apologies up front if this is something on my end. 

`wm = Wordmesh(text)`
`wm.plot()` or ` wm.save_as_html(filename='my-wordmesh.html')` produces the following error on Windows 10 and Ubuntu 16.04:

ValueError: 
* Invalid value of type **builtins.str** received for the **textposition** property of scatter
        Received value: _centre_ 

The **textposition** property is an enumeration that may be specified as:
 * One of the following enumeration values:
            ['top left', 'top center', 'top right', 'middle left',
            'middle center', 'middle right', 'bottom left', 'bottom
            center', 'bottom right']
 * A tuple, list, or one-dimensional numpy array of the above

Not sure if this is an issue with Plotly==3.0.0. Any assistance is appreciated. And nice work picking spacy/textacy.

**Comment by mukund109** [comment]
Yes this is an issue with plotly 3.0.0
Check out [Issue #1](https://github.com/mukund109/word-mesh/issues/1)
Try downgrading plotly, that should fix it.

**Comment by evolving6000** [comment]
Sorry I should have checked the requirements file first. Working now. Very
cool program.

**Comment by casahome2000** [comment]
pip3 install plotly==2.7.0
so save a google search

**Comment by SingASongForME** [comment]
The 'textposition' property is an enumeration that may be specified as:
      - One of the following enumeration values:
For value- outside or top center or any value , it is not working in 4.9.0

**Comment by shihs** [comment]
Change the 'textposition' property to 'to center' works for `plotly==5.0.0`

**Comment by Y5563** [comment]
i have an issue plotting geograpical plotly this is the erro i got when plotting the graph
i import plotly.graph_objs as go
but i am still getting this error pls how can i solve this erro?
NameError                                 Traceback (most recent call last)
<ipython-input-1-85ee71a6d940> in <module>
----> 1 x = go.Figure(data=[data], layout =layout)

NameError: name 'go' is not defined
